eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/feign?token=2019
server:
  port: 8093
spring:
  application:
    name: spc.liangzai.zuul
  zipkin:
      base-url: http://47.104.94.13:8065
zuul:
  routes:
    api-a:
      path: /ribbon/**
      serviceId: spc.liangzai.ribbon
    api-b:
      path: /feign/**
      serviceId: spc.liangzai.feign
